### ISSUE TITLE
[Component] Timeline stack chart visualization

### ISSUE THREAD

**Issue by Th1nkK1D** [electinth/cda#2]
![image](https://user-images.githubusercontent.com/8860448/111426508-54233580-8727-11eb-99d1-6bad066e2ca0.png)

- Have 3 steps: 1st pin drop, 1st stack chart appear and 2nd stack chart appear together when 2nd pin drop
- Each step will be in a different section of the page
- Play transition animation from the last step to the current step when the component shown in the viewport
- Description under each chart should be a slot for customization
- Replay button is nice to have

**Comment by thasarito** [comment]
is the data for this part ready? @Th1nkK1D

**Comment by Th1nkK1D** [comment]
> is the data for this part ready? @Th1nkK1D 

Let me confirm this with the team ASAP

**Comment by thasarito** [comment]
To-dos:

- [x] Add slot for chart label

**Comment by thasarito** [comment]
@Th1nkK1D Sorry, I messed up git. Your latest commit got changed a little.

**Comment by thasarito** [comment]
Still need to update text.

**Comment by Th1nkK1D** [comment]
@thasarito Doesn't look like a big problem. Text (and some layout/transition) are updated.
